### ISSUE TITLE
GL/glx.h  is missing . . .

### ISSUE THREAD

**Issue by paroj** [paroj/gltut#55]
Originally reported by: **Anonymous**

---

Hi Jason,

The tutorials look excellent. Thanks for creating them.

I'm working on Ubuntu 12.04,
and am following the instructions in the Building the Tutorials section.

This appearantly worked:
in glsdk
    premake4 gmake

The errors I'm getting are when attempting to build in the glsdk directory:

>  make config=debug all

==== Building glload (debug) ====
gll_gl_ext.c
source/gll_gl_ext.c:251:26: fatal error: GL/glx.h: No such file or directory
compilation terminated.
make[1]: **\* [Debug/gll_gl_ext.o] Error 1

regards,
-jg-

John Gibson
Toronto

---
- Bitbucket: https://bitbucket.org/alfonse/gltut/issue/86
