### ISSUE TITLE
Tutorials 12 and 16 do not build with GCC 4.7

### ISSUE THREAD

**Issue by paroj** [paroj/gltut#44]
Originally reported by: **Nikos Platis (Bitbucket: [nplatis](http://bitbucket.org/nplatis), GitHub: [nplatis](http://github.com/nplatis))**

---

The error messages for tutorial 12 are

```
In file included from Lights.h:12:0,
                 from Lights.cpp:13:
../framework/Interpolators.h: In instantiation of ‘void Framework::ConstVelLinearInterpolator<ValueType>::SetValues(const BidirectionalRange&, bool) [with BidirectionalRange = std::vector<glm::detail::tvec3<float> >; ValueType = glm::detail::tvec3<float>]’:
Lights.cpp:66:35:   required from here

../framework/Interpolators.h:183:5: error: ‘distance’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]

Lights.cpp:38:7: note: ‘float distance(const vec3&, const vec3&)’ declared here, later in the translation unit
```

and similarly for

```
Lights.cpp:133:7: note: ‘float GetValue(const MaxIntensityData&)’ declared here, later in the translation unit
```

and

```
Lights.cpp:134:7: note: ‘float GetTime(const MaxIntensityData&)’ declared here, later in the translation unit
```

This is due to a change in (incorrect) behavior of gcc, as documented in http://gcc.gnu.org/bugzilla/show_bug.cgi?id=29131
and the solution is to (at least) declare these functions before including "Lights.h" (or actually before including "../framework/Interpolators.h").

In tutorial 16 (LightEnv.cpp) this is accomplished by simply moving the #include "LightEnv.h" after the definition of distance().

In tutorial 12 (Lights.cpp) you could move all declarations of these functions at the top (just like in tutorial 16/LightEnv.cpp) and also move the #include "Lights.h" below them.

---
- Bitbucket: https://bitbucket.org/alfonse/gltut/issue/75
